using NUnit.Framework;


namespace UserGenerator
{

    /// <summary>
    /// Create email
    /// Create firstname
    /// Create lastname
    /// Create password
    /// </summary>
    public class GenerateUsers
    {

        public static readonly string userpath = TestContext.Parameters["AutogeneratedUsersPath"];
       

        public UserModel CreateUser()
        {
            var random = TestContext.CurrentContext.Random;
            
            int rnd = random.Next(200);

            string email = "TestVolo_" + rnd + "volo.test";
            string firstname = "Test" + rnd;
            string lastname = "Volo" + rnd;
            string password = "TestVolo12!";

            return new UserModel(email, firstname, lastname, password);
        }

    }


}
